// UI-7 -- Section H: a concise, static explanation of what these
// analytics are and are not -- the same "honest, non-claiming static
// explanation" pattern results/DecisionExplanation.jsx (UI-5) already
// established for its own pipeline explanation, reused here for a
// different, insights-specific message.

function MethodologyNote() {
  return (
    <section className="page-section">
      <h2 className="section-title">What These Analytics Mean</h2>
      <ul className="methodology-note-list">
        <li className="text-small">These figures describe your own past analyzed procurement runs only.</li>
        <li className="text-small">They are historical observations, not predictions, forecasts, or guarantees.</li>
        <li className="text-small">
          "Expected savings" is the collaborative-procurement value the decision engine computed for a run — it does
          not mean that purchase was actually carried out or that money was realized.
        </li>
        <li className="text-small">No score, ranking, or recommendation here is generated by AI — every figure is a plain count or sum.</li>
      </ul>
    </section>
  );
}

export default MethodologyNote;
